"""create all tables

Revision ID: 4a6a1840e3c7
Revises: 
Create Date: 2026-06-25 04:27:13.837313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a6a1840e3c7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('company_code', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('slug', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('logo', sa.String(), nullable=True))
    op.create_index(op.f('ix_companies_company_code'), 'companies', ['company_code'], unique=True)
    op.create_unique_constraint(None, 'companies', ['slug'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'companies', type_='unique')
    op.drop_index(op.f('ix_companies_company_code'), table_name='companies')
    op.drop_column('companies', 'logo')
    op.drop_column('companies', 'slug')
    op.drop_column('companies', 'company_code')
    # ### end Alembic commands ###
