"""create all tables

Revision ID: 4a6a1840e3c7
Revises: 
Create Date: 2026-06-25 04:27:13.837313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '4a6a1840e3c7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.

    Guarded: this is one of two independent migration roots (the other is
    6ca8a12ad101 -> b1c2d3e4f5a6). On a fresh DB Alembic may run either
    root first, so this checks what's already there instead of assuming
    a clean slate — safe no matter which branch got there first.
    """
    conn = op.get_bind()

    has_company_code = conn.execute(sa.text(
        "SELECT 1 FROM information_schema.columns "
        "WHERE table_name = 'companies' AND column_name = 'company_code'"
    )).first()
    if not has_company_code:
        op.add_column('companies', sa.Column('company_code', sa.String(), nullable=True))

    has_slug = conn.execute(sa.text(
        "SELECT 1 FROM information_schema.columns "
        "WHERE table_name = 'companies' AND column_name = 'slug'"
    )).first()
    if not has_slug:
        op.add_column('companies', sa.Column('slug', sa.String(), nullable=True))

    has_logo = conn.execute(sa.text(
        "SELECT 1 FROM information_schema.columns "
        "WHERE table_name = 'companies' AND column_name = 'logo'"
    )).first()
    if not has_logo:
        op.add_column('companies', sa.Column('logo', sa.String(), nullable=True))

    has_company_code_index = conn.execute(sa.text(
        "SELECT 1 FROM pg_indexes "
        "WHERE tablename = 'companies' AND indexname = 'ix_companies_company_code'"
    )).first()
    if not has_company_code_index:
        op.create_index(op.f('ix_companies_company_code'), 'companies', ['company_code'], unique=True)

    has_slug_constraint = conn.execute(sa.text(
        "SELECT 1 FROM information_schema.table_constraints "
        "WHERE table_name = 'companies' AND constraint_type = 'UNIQUE' "
        "AND constraint_name = 'companies_slug_key'"
    )).first()
    if not has_slug_constraint:
        op.create_unique_constraint('companies_slug_key', 'companies', ['slug'])


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('companies_slug_key', 'companies', type_='unique')
    op.drop_index(op.f('ix_companies_company_code'), table_name='companies')
    op.drop_column('companies', 'logo')
    op.drop_column('companies', 'slug')
    op.drop_column('companies', 'company_code')
    # ### end Alembic commands ###