"""day39_resolution_note

Revision ID: 623cc54d0b7f
Revises: ec79b0567b55
Create Date: 2026-10-03 04:01:36.711802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '623cc54d0b7f'
down_revision: Union[str, Sequence[str], None] = 'ec79b0567b55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('maintenance_tickets', sa.Column('resolution_note', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('maintenance_tickets', 'resolution_note')
    # ### end Alembic commands ###
