"""add full_name and phone to users

Revision ID: a07387b0db1a
Revises: 6ca8a12ad101
Create Date: 2026-05-30 10:11:55.385278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a07387b0db1a'
down_revision: Union[str, Sequence[str], None] = '6ca8a12ad101'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('companies', 'logo',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_constraint(op.f('companies_company_code_key'), 'companies', type_='unique')
    op.create_index(op.f('ix_companies_company_code'), 'companies', ['company_code'], unique=True)
    op.add_column('users', sa.Column('full_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('phone', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone')
    op.drop_column('users', 'full_name')
    op.drop_index(op.f('ix_companies_company_code'), table_name='companies')
    op.create_unique_constraint(op.f('companies_company_code_key'), 'companies', ['company_code'], postgresql_nulls_not_distinct=False)
    op.alter_column('companies', 'logo',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
